title: Blog
author: Janina Volkmer
email: janina.volkmer@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Hi! 
  I'm Janina, a junior backend developer from Amsterdam. 
  I've started this blog to keep track of my own projects and to show what I'm working on

# social links
twitter_username: Janina_Volkmer # DO NOT include the @ character, or else the build will fail!
github_username:  JaninaVolkmer # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
